export const COUNTRIES = [
  "Uganda",
  "Italy",
  "United States",
  "United Kingdom",
  "France",
  "Germany",
  "South Africa",
  "Morocco",
  "Tanzania",
  "Kenya",
  "Nigeria",
  "Ghana",
  "Egypt",
  "Canada",
  "Australia",
  "Netherlands",
  "Spain",
  "Switzerland",
  "United Arab Emirates",
  "India",
  "Other",
] as const;

export const PHONE_CODES = [
  { code: "+1", label: "+1" },
  { code: "+44", label: "+44" },
  { code: "+39", label: "+39" },
  { code: "+256", label: "+256" },
  { code: "+33", label: "+33" },
  { code: "+49", label: "+49" },
  { code: "+27", label: "+27" },
  { code: "+212", label: "+212" },
  { code: "+255", label: "+255" },
  { code: "+254", label: "+254" },
  { code: "+234", label: "+234" },
  { code: "+233", label: "+233" },
  { code: "+20", label: "+20" },
  { code: "+91", label: "+91" },
  { code: "+971", label: "+971" },
  { code: "+61", label: "+61" },
  { code: "+31", label: "+31" },
  { code: "+34", label: "+34" },
  { code: "+41", label: "+41" },
  { code: "+86", label: "+86" },
  { code: "+81", label: "+81" },
  { code: "+55", label: "+55" },
  { code: "+52", label: "+52" },
  { code: "+7", label: "+7" },
  { code: "+82", label: "+82" },
] as const;

/** Country name + dial code + flag emoji for phone field; selecting sets dial code automatically. */
export const COUNTRY_PHONE = [
  { name: "Uganda", code: "+256", flag: "🇺🇬" },
  { name: "Italy", code: "+39", flag: "🇮🇹" },
  { name: "United States", code: "+1", flag: "🇺🇸" },
  { name: "United Kingdom", code: "+44", flag: "🇬🇧" },
  { name: "France", code: "+33", flag: "🇫🇷" },
  { name: "Germany", code: "+49", flag: "🇩🇪" },
  { name: "South Africa", code: "+27", flag: "🇿🇦" },
  { name: "Morocco", code: "+212", flag: "🇲🇦" },
  { name: "Tanzania", code: "+255", flag: "🇹🇿" },
  { name: "Kenya", code: "+254", flag: "🇰🇪" },
  { name: "Nigeria", code: "+234", flag: "🇳🇬" },
  { name: "Ghana", code: "+233", flag: "🇬🇭" },
  { name: "Egypt", code: "+20", flag: "🇪🇬" },
  { name: "Canada", code: "+1", flag: "🇨🇦" },
  { name: "Australia", code: "+61", flag: "🇦🇺" },
  { name: "Netherlands", code: "+31", flag: "🇳🇱" },
  { name: "Spain", code: "+34", flag: "🇪🇸" },
  { name: "Switzerland", code: "+41", flag: "🇨🇭" },
  { name: "United Arab Emirates", code: "+971", flag: "🇦🇪" },
  { name: "India", code: "+91", flag: "🇮🇳" },
  { name: "Peru", code: "+51", flag: "🇵🇪" },
  { name: "Japan", code: "+81", flag: "🇯🇵" },
  { name: "China", code: "+86", flag: "🇨🇳" },
  { name: "Brazil", code: "+55", flag: "🇧🇷" },
  { name: "Mexico", code: "+52", flag: "🇲🇽" },
  { name: "Russia", code: "+7", flag: "🇷🇺" },
  { name: "South Korea", code: "+82", flag: "🇰🇷" },
] as const;
